### ISSUE TITLE
the hells the download icon at .-. i didn't wanna fork this i just wanted a file for my mod folder

### ISSUE THREAD

**Issue by xEightsx** [Nanakra/Rakkle-1.3#1]
Point me in the right direction....

**Comment by Nanakra** [comment]
Hi xEightsx.
Git Hub is a bit odd with its download buttons.
To download you need to click the Code button and then the link for Download as zip.
But you can hit this link as that is where it sends you: https://github.com/Nanakra/Rakkle-1.3/archive/refs/heads/master.zip
